### ISSUE TITLE
WARNING: Please indicate the backup path in the module's configuration. The path must already exists on the system.

### ISSUE THREAD

**Issue by krzyszaf** [esaracco/wbmclamav#1]
I don't know how to fix it. Maybe any ideas of it? I can't find the place where is it.

**Comment by esaracco** [comment]
Open the module config page and fill "Backup directory (should not be a temporary directory)" with a path that exists on your system (if not, create it before).

**Comment by esaracco** [comment]
There was an error in the module configuration that hid important options! Please, install the latest version and tell me if you see the "Backup directory" option now.
