### ISSUE TITLE
V. 0.21.1 not compatible with ClamAV 0.100.3?

### ISSUE THREAD

**Issue by akwala** [esaracco/wbmclamav#2]
With v. 0.21.1 installed in Webmin, I get an error message saying 

> Your version of ClamAV is not compatible with this module. 

I have ClamAV 0.100.3 which is what the [Ubuntu Bionic/18.04 repo](https://launchpad.net/ubuntu/+source/clamav) has.

![Screenshot_2019-08-23 ClamAV Antivirus ClamAV Antivirus management — Webmin 1 930 (Ubuntu Linux 18 04 3)](https://user-images.githubusercontent.com/1786/63620382-16980e00-c5bf-11e9-809a-7c3c1b105bc5.png)

**Comment by esaracco** [comment]
Indeed, wbmclamav 0.21.1 is not compatible with ClamAV versions less than 0.101.2.

**Comment by akwala** [comment]
> Indeed, wbmclamav 0.21.1 is not compatible with ClamAV versions less than 0.101.2.

Which is the latest version that is compatible with ClamAV 0.100.3? (Ubuntu [does not provide ClamAV 0.101.* in its repo until 19.10/Eoan](https://launchpad.net/ubuntu/+source/clamav) which is to be released in Oct 2019.)

**Comment by esaracco** [comment]
wbmclamav 0.18 is compatible with ClamAV >= 0.100.2, but this is really a old buggy release.
