### ISSUE TITLE
Missing module GD::Graph::lines

### ISSUE THREAD

**Issue by dimmuboy** [esaracco/wbmclamav#3]
Webmin module still shows error about missing perl module **GD::Graph::lines** but it's installed and updated
```
cpan[1]> install GD::Graph::lines
GD::Graph::lines is up to date (1.15).
```

**Comment by githuborer** [comment]
Hmmm, for me webmin and this module are running fine on Debian9
Here is a list of my Perl modules installed:

https://pastebin.com/HkWVpm8q

**Comment by dimmuboy** [comment]
Thanks, it's probably 
GD::Text | 2 | Text utilities for use with GD
I installed it and now it works without any problems.
