### ISSUE TITLE
New version alert shows version older than the one installed

### ISSUE THREAD

**Issue by akwala** [esaracco/wbmclamav#4]
I have the latest version (ClamAV 0.102.4 / wbmclamav 0.22.1) but the alert is for wbmclamav 0.21.1.
![image](https://user-images.githubusercontent.com/1786/106528370-a6c9ca80-64b6-11eb-91fe-bc6ec2959095.png)

**Comment by esaracco** [comment]
@akwala Sorry for the delay. It should be fixed now. Thanks!

**Comment by akwala** [comment]
> @akwala Sorry for the delay. It should be fixed now. Thanks!

Yep, alert doesn't appear (I have the latest version).
