### ISSUE TITLE
Please fill in the location of the ClamAV Daemon

### ISSUE THREAD

**Issue by BlueH2O** [esaracco/wbmclamav#5]
I cannot get past this warning:
Warning : Please fill in the location of the ClamAV Daemon (clamd) log file in the module's configuration.
I must assume this means "Daemon init script path (if sysvinit)" because there does not appear to be a configuration item that asks for the location of clamd.  And since the system is NOT sysvinit....

I've tried /usr/sbin/clamd and several other values; the warning remains.

Perhaps it's not correctly detecting systemd?

**Comment by esaracco** [comment]
What is the logfile of your ClamAV daemon?
You can update it in the "ClamAV" category of the module's conf ("Logfile path"):

![conf](https://user-images.githubusercontent.com/4351162/133207488-8885afed-e876-401d-bdef-e799b1d10f5c.png)

**Comment by BlueH2O** [comment]
OK, so, I misread it.  I apologize.
