### ISSUE TITLE
Error with the github zip archive of the master branch 

### ISSUE THREAD

**Issue by WhiteTiger-IT** [esaracco/wbmclamav#6]
Hi,
I downloaded the wbmclamav-master.zip file, but when I upload it in Webmin (1.982) I get the error:
`Failed to install uploaded module : Not a valid module file : tar: This does not look like a tar archive tar: Skipping to next header tar: Exiting with failure status due to previous errors
`
The server is a Debian 11.

**Comment by esaracco** [comment]
webmin only accept tar compressed files. If you do not know how to rebuild it from the github zip archive, just download the latest module here: https://wbmclamav.esaracco.fr/download/
