### ISSUE TITLE
ClamAV compatibility

### ISSUE THREAD

**Issue by wac02** [esaracco/wbmclamav#7]
Ubuntu 20, ClamAV 0.103.2

When first opening the module I receive the error " Warning : Your version of ClamAV is not compatible with this module. Please check that you have installed a recent enough version of ClamAV."

Debugger tells me though; "The resource from “https://172.16.1.100:10000/css/clamav.css?0.23” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)."

Please advise.

**Comment by esaracco** [comment]
You should install at least ClamAV 0.103.3 (I will fix css warning soon).
